In [3]:
import pandas as pd
orders=pd.Series(["Delivered","Cancelled","Delivered","Pending"])
print(orders.dtype)

object


In [4]:
import pandas as pd
orders=pd.Series(["Delivered","Cancelled","Delivered","Pending"])
print(orders.dtype)
orders=orders.astype("category")
print(orders.dtype)

object
category


In [8]:
salary=[1000,2000,3000,5000]
new_salary=[]
for s in salary:
    new_salary.append(s*2.3)
print(new_salary)

[2300.0, 4600.0, 6899.999999999999, 11500.0]


In [9]:
import numpy as np
salary=np.array([100,200,300,400,700])
new_salary=salary*1.1
print(new_salary)

[110. 220. 330. 440. 770.]


In [10]:
import numpy as np
price=np.array([200,300,400,600])
new_price=price*5.0
print(new_price)

[1000. 1500. 2000. 3000.]


In [12]:
import numpy as np
price=np.array([200,300,400,600])
discount_price=price*0.5
print(discount_price)

[100. 150. 200. 300.]


In [14]:
import pandas as pd
data=pd.Series(range(1,10))
sample=data.sample(6)
print(sample)

3    4
2    3
0    1
7    8
6    7
4    5
dtype: int64


In [15]:
sample=data.sample(frac=0.2)
print(sample)

4    5
2    3
dtype: int64


In [16]:
sample=data.sample(frac=0.5)
print(sample)

6    7
4    5
0    1
2    3
dtype: int64
